"""
Copyright (c) 2026, Oracle and/or its affiliates.
Licensed under the Universal Permissive License v1.0 as shown at
https://oss.oracle.com/licenses/upl.
"""

from __future__ import annotations

from pathlib import Path

DEFAULT_RUNTIME_DIR = Path.home() / ".oci-vision-mcp"
DEFAULT_SESSION_AUTH_COMMAND = "oci"
SESSION_AUTH_COMMAND_ENV = "OCI_SESSION_AUTH_COMMAND"
DEFAULT_MAX_IMAGE_BYTES = 10 * 1024 * 1024
DEFAULT_REFRESH_SESSION = True
DEFAULT_AUTO_AUTH = False
DEFAULT_EXPIRY_SKEW_SECONDS = 300
DEFAULT_RESULT_TTL_SECONDS = 7 * 24 * 60 * 60
DEFAULT_MAX_INLINE_RESPONSE_BYTES = 20_000
DEFAULT_DETAIL = "summary"
DEFAULT_OBJECT_STORAGE_OVERWRITE = False
DEFAULT_OBJECT_STORAGE_DOWNLOAD_SUBDIR = "obj_results"
DEFAULT_OBJECT_STORAGE_FETCH_MAX_BYTES = 50 * 1024 * 1024
DEFAULT_RESULT_STORE_DIR = DEFAULT_RUNTIME_DIR / "results"
DEFAULT_LOG_DIR = DEFAULT_RUNTIME_DIR / "logs"
DEFAULT_OBJECT_STORAGE_DOWNLOAD_DIR = DEFAULT_RUNTIME_DIR / DEFAULT_OBJECT_STORAGE_DOWNLOAD_SUBDIR
DEFAULT_ENABLE_URL_INPUTS = False
DEFAULT_URL_MAX_REDIRECTS = 3
DEFAULT_URL_CONNECT_TIMEOUT_SECONDS = 3.0
DEFAULT_URL_READ_TIMEOUT_SECONDS = 10.0
DEFAULT_ALLOWED_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".gif",
    ".tif",
    ".tiff",
    ".webp",
}

MAX_TOOL_MAX_ITEMS = 100
MAX_PARALLEL_ANALYZE_ITEMS = 50
MAX_PARALLEL_ANALYZE_MAX_PARALLEL = 25
MAX_IMAGE_JOB_OBJECTS = 1000
MAX_IMAGE_JOB_REQUEST_BYTES = 500_000
MAX_OBJECT_STORAGE_BULK_UPLOAD_IMAGES = 100
MAX_OBJECT_STORAGE_BULK_FETCH_OBJECTS = 100
MAX_OBJECT_STORAGE_LIST_PAGE_SIZE = 1000
MAX_OBJECT_STORAGE_LIST_END_INDEX = 10_000
MAX_OBJECT_STORAGE_LIST_RANGE_SIZE = 1000
MAX_OBJECT_STORAGE_LIST_SCAN_PAGES = 25

FEATURE_IMAGE_CLASSIFICATION = "IMAGE_CLASSIFICATION"
FEATURE_OBJECT_DETECTION = "OBJECT_DETECTION"
FEATURE_FACE_DETECTION = "FACE_DETECTION"
FEATURE_TEXT_DETECTION = "TEXT_DETECTION"

TOOL_ANALYZE_IMAGE = "analyze_image"
TOOL_PARALLEL_ANALYZE_IMAGE = "parallel_analyze_image"
TOOL_CLASSIFY_IMAGE = "classify_image"
TOOL_DETECT_OBJECTS = "detect_objects"
TOOL_DETECT_FACES = "detect_faces"
TOOL_DETECT_TEXT = "detect_text"
TOOL_CREATE_IMAGE_JOB = "create_image_job"
TOOL_GET_IMAGE_JOB = "get_image_job"
TOOL_CANCEL_IMAGE_JOB = "cancel_image_job"
TOOL_UPLOAD_IMAGE_TO_OBJECT_STORAGE = "upload_image_to_object_storage"
TOOL_LIST_OBJECT_STORAGE_OBJECTS = "list_object_storage_objects"
TOOL_FETCH_OBJECT_STORAGE_OBJECT = "fetch_object_storage_object"
TOOL_GET_CONFIG_STATUS = "get_config_status"
TOOL_GET_ANALYSIS_RESULT = "get_analysis_result"
