apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-js-host
  namespace: oci-js-host
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-js-runner
  namespace: oci-js-execution
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-js-kata-reconciler
  namespace: oci-js-host
automountServiceAccountToken: true
