"""
Copyright (c) 2026, Oracle and/or its affiliates.
Licensed under the Universal Permissive License v1.0 as shown at
https://oss.oracle.com/licenses/upl.
"""

from __future__ import annotations

BOOTSTRAP_TOOL_NAMES = frozenset(
    {
        "get_compartment",
        "list_compartments",
    }
)
REQUEST_MODEL_TYPES = {
    ('change_autonomous_database_insight_advanced_features', 'change_autonomous_database_insight_advanced_features_details'): 'ChangeAutonomousDatabaseInsightAdvancedFeaturesDetails',
    ('change_awr_hub_source_compartment', 'change_awr_hub_source_compartment_details'): 'ChangeAwrHubSourceCompartmentDetails',
    ('change_chargeback_plan_compartment', 'change_chargeback_plan_compartment_details'): 'ChangeChargebackPlanCompartmentDetails',
    ('change_database_insight_compartment', 'change_database_insight_compartment_details'): 'ChangeDatabaseInsightCompartmentDetails',
    ('change_enterprise_manager_bridge_compartment', 'change_enterprise_manager_bridge_compartment_details'): 'ChangeEnterpriseManagerBridgeCompartmentDetails',
    ('change_exadata_insight_compartment', 'change_exadata_insight_compartment_details'): 'ChangeExadataInsightCompartmentDetails',
    ('change_host_insight_compartment', 'change_host_insight_compartment_details'): 'ChangeHostInsightCompartmentDetails',
    ('change_macs_managed_autonomous_database_insight_connection', 'change_macs_managed_autonomous_database_insight_connection_details'): 'ChangeMacsManagedAutonomousDatabaseInsightConnectionDetails',
    ('change_macs_managed_cloud_database_insight_connection', 'change_macs_managed_cloud_database_insight_connection_details'): 'ChangeMacsManagedCloudDatabaseInsightConnectionDetails',
    ('change_news_report_compartment', 'change_news_report_compartment_details'): 'ChangeNewsReportCompartmentDetails',
    ('change_operations_insights_private_endpoint_compartment', 'change_operations_insights_private_endpoint_compartment_details'): 'ChangeOperationsInsightsPrivateEndpointCompartmentDetails',
    ('change_operations_insights_warehouse_compartment', 'change_operations_insights_warehouse_compartment_details'): 'ChangeOperationsInsightsWarehouseCompartmentDetails',
    ('change_opsi_configuration_compartment', 'change_opsi_configuration_compartment_details'): 'ChangeOpsiConfigurationCompartmentDetails',
    ('change_pe_comanaged_database_insight', 'change_pe_comanaged_database_insight_details'): 'ChangePeComanagedDatabaseInsightDetails',
    ('create_awr_hub', 'create_awr_hub_details'): 'CreateAwrHubDetails',
    ('create_awr_hub_source', 'create_awr_hub_source_details'): 'CreateAwrHubSourceDetails',
    ('create_chargeback_plan', 'create_chargeback_plan_details'): 'CreateChargebackPlanDetails',
    ('create_chargeback_plan_report', 'create_chargeback_plan_report_details'): 'CreateChargebackPlanReportDetails',
    ('create_database_insight', 'create_database_insight_details'): 'CreateDatabaseInsightDetails',
    ('create_enterprise_manager_bridge', 'create_enterprise_manager_bridge_details'): 'CreateEnterpriseManagerBridgeDetails',
    ('create_exadata_insight', 'create_exadata_insight_details'): 'CreateExadataInsightDetails',
    ('create_host_insight', 'create_host_insight_details'): 'CreateHostInsightDetails',
    ('create_news_report', 'create_news_report_details'): 'CreateNewsReportDetails',
    ('create_operations_insights_private_endpoint', 'create_operations_insights_private_endpoint_details'): 'CreateOperationsInsightsPrivateEndpointDetails',
    ('create_operations_insights_warehouse', 'create_operations_insights_warehouse_details'): 'CreateOperationsInsightsWarehouseDetails',
    ('create_operations_insights_warehouse_user', 'create_operations_insights_warehouse_user_details'): 'CreateOperationsInsightsWarehouseUserDetails',
    ('create_opsi_configuration', 'create_opsi_configuration_details'): 'CreateOpsiConfigurationDetails',
    ('enable_autonomous_database_insight_advanced_features', 'enable_autonomous_database_insight_advanced_features_details'): 'EnableAutonomousDatabaseInsightAdvancedFeaturesDetails',
    ('enable_database_insight', 'enable_database_insight_details'): 'EnableDatabaseInsightDetails',
    ('enable_exadata_insight', 'enable_exadata_insight_details'): 'EnableExadataInsightDetails',
    ('enable_host_insight', 'enable_host_insight_details'): 'EnableHostInsightDetails',
    ('enable_plan_exadata_insight', 'enable_plan_exadata_insight_details'): 'EnablePlanExadataInsightDetails',
    ('query_opsi_data_object_data', 'query_opsi_data_object_data_details'): 'QueryOpsiDataObjectDataDetails',
    ('query_warehouse_data_object_data', 'query_warehouse_data_object_data_details'): 'QueryWarehouseDataObjectDataDetails',
    ('update_awr_hub', 'update_awr_hub_details'): 'UpdateAwrHubDetails',
    ('update_awr_hub_source', 'update_awr_hub_source_details'): 'UpdateAwrHubSourceDetails',
    ('update_chargeback_plan', 'update_chargeback_plan_details'): 'UpdateChargebackPlanDetails',
    ('update_chargeback_plan_report', 'update_chargeback_plan_report_details'): 'UpdateChargebackPlanReportDetails',
    ('update_database_insight', 'update_database_insight_details'): 'UpdateDatabaseInsightDetails',
    ('update_enterprise_manager_bridge', 'update_enterprise_manager_bridge_details'): 'UpdateEnterpriseManagerBridgeDetails',
    ('update_exadata_insight', 'update_exadata_insight_details'): 'UpdateExadataInsightDetails',
    ('update_host_insight', 'update_host_insight_details'): 'UpdateHostInsightDetails',
    ('update_news_report', 'update_news_report_details'): 'UpdateNewsReportDetails',
    ('update_operations_insights_private_endpoint', 'update_operations_insights_private_endpoint_details'): 'UpdateOperationsInsightsPrivateEndpointDetails',
    ('update_operations_insights_warehouse', 'update_operations_insights_warehouse_details'): 'UpdateOperationsInsightsWarehouseDetails',
    ('update_operations_insights_warehouse_user', 'update_operations_insights_warehouse_user_details'): 'UpdateOperationsInsightsWarehouseUserDetails',
    ('update_opsi_configuration', 'update_opsi_configuration_details'): 'UpdateOpsiConfigurationDetails',
}
INCLUDED_METHOD_NAMES = (
    'change_autonomous_database_insight_advanced_features',
    'change_awr_hub_source_compartment',
    'change_chargeback_plan_compartment',
    'change_database_insight_compartment',
    'change_enterprise_manager_bridge_compartment',
    'change_exadata_insight_compartment',
    'change_host_insight_compartment',
    'change_macs_managed_autonomous_database_insight_connection',
    'change_macs_managed_cloud_database_insight_connection',
    'change_news_report_compartment',
    'change_operations_insights_private_endpoint_compartment',
    'change_operations_insights_warehouse_compartment',
    'change_opsi_configuration_compartment',
    'change_pe_comanaged_database_insight',
    'create_awr_hub',
    'create_awr_hub_source',
    'create_chargeback_plan',
    'create_chargeback_plan_report',
    'create_database_insight',
    'create_enterprise_manager_bridge',
    'create_exadata_insight',
    'create_host_insight',
    'create_news_report',
    'create_operations_insights_private_endpoint',
    'create_operations_insights_warehouse',
    'create_operations_insights_warehouse_user',
    'create_opsi_configuration',
    'disable_autonomous_database_insight_advanced_features',
    'disable_awr_hub_source',
    'disable_database_insight',
    'disable_exadata_insight',
    'disable_host_insight',
    'disable_plan_exadata_insight',
    'enable_autonomous_database_insight_advanced_features',
    'enable_awr_hub_source',
    'enable_database_insight',
    'enable_exadata_insight',
    'enable_host_insight',
    'enable_plan_exadata_insight',
    'get_awr_database_report',
    'get_awr_database_sql_report',
    'get_awr_hub',
    'get_awr_hub_object',
    'get_awr_hub_source',
    'get_awr_report',
    'get_chargeback_plan',
    'get_chargeback_plan_report',
    'get_chargeback_plan_report_content',
    'get_database_insight',
    'get_enterprise_manager_bridge',
    'get_exadata_insight',
    'get_host_insight',
    'get_news_report',
    'get_operations_insights_private_endpoint',
    'get_operations_insights_warehouse',
    'get_operations_insights_warehouse_user',
    'get_opsi_configuration',
    'get_opsi_data_object',
    'get_work_request',
    'list_addm_db_finding_categories',
    'list_addm_db_findings_time_series',
    'list_addm_db_parameter_categories',
    'list_addm_db_recommendation_categories',
    'list_addm_db_recommendations_time_series',
    'list_addm_dbs',
    'list_awr_database_snapshots',
    'list_awr_databases',
    'list_awr_hub_objects',
    'list_awr_hub_sources',
    'list_awr_hubs',
    'list_awr_snapshots',
    'list_chargeback_plan_reports',
    'list_chargeback_plans',
    'list_database_configurations',
    'list_database_insights',
    'list_enterprise_manager_bridges',
    'list_exadata_configurations',
    'list_exadata_insights',
    'list_host_configurations',
    'list_host_insights',
    'list_hosted_entities',
    'list_importable_agent_entities',
    'list_importable_compute_entities',
    'list_importable_enterprise_manager_entities',
    'list_news_reports',
    'list_operations_insights_private_endpoints',
    'list_operations_insights_warehouse_users',
    'list_operations_insights_warehouses',
    'list_opsi_configurations',
    'list_opsi_data_objects',
    'list_sql_plans',
    'list_sql_texts',
    'list_warehouse_data_objects',
    'list_work_request_errors',
    'list_work_request_logs',
    'list_work_requests',
    'query_opsi_data_object_data',
    'query_warehouse_data_object_data',
    'summarize_addm_db_findings',
    'summarize_addm_db_parameter_changes',
    'summarize_addm_db_parameters',
    'summarize_addm_db_recommendations',
    'summarize_addm_db_schema_objects',
    'summarize_addm_db_sql_statements',
    'summarize_awr_database_cpu_usages',
    'summarize_awr_database_metrics',
    'summarize_awr_database_parameter_changes',
    'summarize_awr_database_parameters',
    'summarize_awr_database_snapshot_ranges',
    'summarize_awr_database_sysstats',
    'summarize_awr_database_top_wait_events',
    'summarize_awr_database_wait_event_buckets',
    'summarize_awr_database_wait_events',
    'summarize_awr_sources_summaries',
    'summarize_configuration_items',
    'summarize_database_insight_resource_capacity_trend',
    'summarize_database_insight_resource_forecast_trend',
    'summarize_database_insight_resource_statistics',
    'summarize_database_insight_resource_usage',
    'summarize_database_insight_resource_usage_trend',
    'summarize_database_insight_resource_utilization_insight',
    'summarize_database_insight_tablespace_usage_trend',
    'summarize_exadata_insight_resource_capacity_trend',
    'summarize_exadata_insight_resource_capacity_trend_aggregated',
    'summarize_exadata_insight_resource_forecast_trend',
    'summarize_exadata_insight_resource_forecast_trend_aggregated',
    'summarize_exadata_insight_resource_statistics',
    'summarize_exadata_insight_resource_usage',
    'summarize_exadata_insight_resource_usage_aggregated',
    'summarize_exadata_insight_resource_utilization_insight',
    'summarize_exadata_members',
    'summarize_host_insight_disk_statistics',
    'summarize_host_insight_host_recommendation',
    'summarize_host_insight_io_usage_trend',
    'summarize_host_insight_network_usage_trend',
    'summarize_host_insight_resource_capacity_trend',
    'summarize_host_insight_resource_forecast_trend',
    'summarize_host_insight_resource_statistics',
    'summarize_host_insight_resource_usage',
    'summarize_host_insight_resource_usage_trend',
    'summarize_host_insight_resource_utilization_insight',
    'summarize_host_insight_storage_usage_trend',
    'summarize_host_insight_top_processes_usage',
    'summarize_host_insight_top_processes_usage_trend',
    'summarize_operations_insights_warehouse_resource_usage',
    'update_awr_hub',
    'update_awr_hub_source',
    'update_chargeback_plan',
    'update_chargeback_plan_report',
    'update_database_insight',
    'update_enterprise_manager_bridge',
    'update_exadata_insight',
    'update_host_insight',
    'update_news_report',
    'update_operations_insights_private_endpoint',
    'update_operations_insights_warehouse',
    'update_operations_insights_warehouse_user',
    'update_opsi_configuration',
)
MUTABLE_METHOD_NAMES = (
    'change_autonomous_database_insight_advanced_features',
    'change_awr_hub_source_compartment',
    'change_chargeback_plan_compartment',
    'change_database_insight_compartment',
    'change_enterprise_manager_bridge_compartment',
    'change_exadata_insight_compartment',
    'change_host_insight_compartment',
    'change_macs_managed_autonomous_database_insight_connection',
    'change_macs_managed_cloud_database_insight_connection',
    'change_news_report_compartment',
    'change_operations_insights_private_endpoint_compartment',
    'change_operations_insights_warehouse_compartment',
    'change_opsi_configuration_compartment',
    'change_pe_comanaged_database_insight',
    'create_awr_hub',
    'create_awr_hub_source',
    'create_chargeback_plan',
    'create_chargeback_plan_report',
    'create_database_insight',
    'create_enterprise_manager_bridge',
    'create_exadata_insight',
    'create_host_insight',
    'create_news_report',
    'create_operations_insights_private_endpoint',
    'create_operations_insights_warehouse',
    'create_operations_insights_warehouse_user',
    'create_opsi_configuration',
    'disable_autonomous_database_insight_advanced_features',
    'disable_awr_hub_source',
    'disable_database_insight',
    'disable_exadata_insight',
    'disable_host_insight',
    'disable_plan_exadata_insight',
    'enable_autonomous_database_insight_advanced_features',
    'enable_awr_hub_source',
    'enable_database_insight',
    'enable_exadata_insight',
    'enable_host_insight',
    'enable_plan_exadata_insight',
    'update_awr_hub',
    'update_awr_hub_source',
    'update_chargeback_plan',
    'update_chargeback_plan_report',
    'update_database_insight',
    'update_enterprise_manager_bridge',
    'update_exadata_insight',
    'update_host_insight',
    'update_news_report',
    'update_operations_insights_private_endpoint',
    'update_operations_insights_warehouse',
    'update_operations_insights_warehouse_user',
    'update_opsi_configuration',
)
TOOL_NAMES = frozenset(INCLUDED_METHOD_NAMES) | BOOTSTRAP_TOOL_NAMES
MUTABLE_TOOL_NAMES = frozenset(MUTABLE_METHOD_NAMES)


TOOL_DESCRIPTIONS = {
    'get_compartment': 'Retrieves an OCI compartment by OCID. Use this operation to validate or resolve compartment scope before listing Operations Insights resources.',
    'list_compartments': 'Lists OCI compartments under a root compartment. Use this operation to discover compartment IDs for subsequent Operations Insights queries.',
    'change_autonomous_database_insight_advanced_features': 'Updates the advanced-feature connection details for an Autonomous Database insight in Operations Insights.',
    'change_awr_hub_source_compartment': 'Moves an AWR Hub source resource to another compartment. Use this operation when the AWR Hub source must be re-scoped without changing its source database registration.',
    'change_chargeback_plan_compartment': 'Moves an Operations Insights chargeback plan resource to another compartment.',
    'change_database_insight_compartment': 'Moves a database insight resource to another compartment. This changes resource placement and does not return database performance metrics.',
    'change_enterprise_manager_bridge_compartment': 'Moves an Operations Insights Enterprise Manager bridge resource to another compartment.',
    'change_exadata_insight_compartment': 'Moves an Exadata insight resource to another compartment. This changes resource placement and does not change Exadata metric summaries.',
    'change_host_insight_compartment': 'Moves a host insight resource to another compartment. This changes resource placement and does not return host performance metrics.',
    'change_macs_managed_autonomous_database_insight_connection': 'Changes connection details for a MACS-managed Autonomous Database insight. Use this operation when the stored connection information must be refreshed or corrected.',
    'change_macs_managed_cloud_database_insight_connection': 'Changes connection details for a Cloud MACS-managed database insight. Use this operation when the stored connection information must be refreshed or corrected.',
    'change_news_report_compartment': 'Moves a news report resource to another compartment.',
    'change_operations_insights_private_endpoint_compartment': 'Moves an Operations Insights private endpoint to another compartment.',
    'change_operations_insights_warehouse_compartment': 'Moves an Operations Insights Warehouse resource to another compartment. Warehouses are normally tenant-scoped and expected in the root compartment.',
    'change_opsi_configuration_compartment': 'Moves an OPSI configuration resource to another compartment.',
    'change_pe_comanaged_database_insight': 'Changes connection details for a private-endpoint co-managed database insight.',
    'create_awr_hub': 'Creates an AWR Hub resource for a tenant in Operations Insights. The resource is expected to be created in the root compartment.',
    'create_awr_hub_source': 'Registers a source database with an AWR Hub so AWR snapshots can be imported and queried through Operations Insights.',
    'create_chargeback_plan': 'Creates an Operations Insights chargeback plan for a resource. Use this operation to define chargeback metering for supported insight resources.',
    'create_chargeback_plan_report': 'Creates a chargeback plan report for an Operations Insights resource.',
    'create_database_insight': 'Creates a database insight resource and enables the database in Operations Insights. Database metric collection and analysis start after enablement.',
    'create_enterprise_manager_bridge': 'Creates an Enterprise Manager bridge in Operations Insights. Use this operation to connect Enterprise Manager-managed entities for import and monitoring.',
    'create_exadata_insight': 'Creates an Exadata insight resource and enables the Exadata system in Operations Insights. Exadata-related metric collection and analysis start after enablement.',
    'create_host_insight': 'Creates a host insight resource and enables the host in Operations Insights. Host metric collection and analysis start after enablement.',
    'create_news_report': 'Creates a news report in Operations Insights. The report is enabled and emailed according to the selected frequency.',
    'create_operations_insights_private_endpoint': 'Creates an Operations Insights private endpoint in a customer compartment. Use this operation when private network access is required for Operations Insights resources.',
    'create_operations_insights_warehouse': 'Creates an Operations Insights Warehouse resource for a tenant. A new ADW is normally provisioned, only one warehouse is expected per tenant, and the warehouse is expected in the root compartment.',
    'create_operations_insights_warehouse_user': 'Creates an Operations Insights Warehouse user resource in the tenant root compartment.',
    'create_opsi_configuration': 'Creates an OPSI configuration resource. Use this operation to define configurable Operations Insights behavior for a compartment or target scope.',
    'disable_autonomous_database_insight_advanced_features': 'Disables advanced features for an Autonomous Database insight and removes the associated direct connection details.',
    'disable_awr_hub_source': 'Disables an AWR Hub source database in Operations Insights and stops AWR data flow for that source.',
    'disable_database_insight': 'Disables a database in Operations Insights and stops database metric collection and analysis.',
    'disable_exadata_insight': 'Disables an Exadata system in Operations Insights and stops Exadata-related metric collection and analysis.',
    'disable_host_insight': 'Disables a host in Operations Insights and stops host metric collection and analysis.',
    'disable_plan_exadata_insight': 'Disables the chargeback plan on an Exadata system and stops metering-related collection and analysis.',
    'enable_autonomous_database_insight_advanced_features': 'Enables advanced features for an Autonomous Database insight and creates the direct connection used for additional collection.',
    'enable_awr_hub_source': 'Enables an AWR Hub source database in Operations Insights and resumes AWR data flow if it was previously stopped.',
    'enable_database_insight': 'Enables a database in Operations Insights and starts database metric collection and analysis.',
    'enable_exadata_insight': 'Enables an Exadata system in Operations Insights and starts Exadata-related metric collection and analysis.',
    'enable_host_insight': 'Enables a host in Operations Insights and starts host metric collection and analysis.',
    'enable_plan_exadata_insight': 'Enables the chargeback plan on an Exadata system and starts metering-related collection and analysis.',
    'get_awr_database_report': 'Retrieves an AWR report for a specified database in an AWR Hub. Use this operation when the user needs the generated AWR report content rather than snapshot metadata.',
    'get_awr_database_sql_report': 'Retrieves a SQL health check report for one SQL statement in a specified AWR database.',
    'get_awr_hub': 'Retrieves details for a specific AWR Hub resource. This returns AWR Hub metadata, not AWR source snapshots or reports.',
    'get_awr_hub_object': 'Retrieves metadata and object content for a specific AWR Hub object.',
    'get_awr_hub_source': 'Retrieves details for a specific AWR Hub source database registration.',
    'get_awr_report': 'Retrieves an AWR report for a specified source database in an AWR Hub. The time range must not exceed seven days, and callers must use either snapshot identifiers or time bounds.',
    'get_chargeback_plan': 'Retrieves details for a specific Operations Insights chargeback plan.',
    'get_chargeback_plan_report': 'Retrieves details for a specific chargeback plan report resource.',
    'get_chargeback_plan_report_content': 'Generates chargeback report content in CSV format for a specified time interval.',
    'get_database_insight': 'Retrieves metadata and lifecycle details for a database insight. This returns the insight resource, not CPU, storage, tablespace, or utilization metrics; use database insight summary operations for those metrics.',
    'get_enterprise_manager_bridge': 'Retrieves details for an Operations Insights Enterprise Manager bridge.',
    'get_exadata_insight': 'Retrieves metadata and lifecycle details for an Exadata insight. This returns the insight resource, not capacity, usage, forecast, or utilization metrics; use Exadata summary operations for those metrics.',
    'get_host_insight': 'Retrieves metadata and lifecycle details for a host insight. This returns the insight resource, not CPU, memory, disk, network, storage, process, or recommendation metrics; use host summary operations for those metrics.',
    'get_news_report': 'Retrieves details for a specific Operations Insights news report.',
    'get_operations_insights_private_endpoint': 'Retrieves details for a specific Operations Insights private endpoint.',
    'get_operations_insights_warehouse': 'Retrieves details for an Operations Insights Warehouse. Only one warehouse is expected per tenant, and it is expected in the root compartment.',
    'get_operations_insights_warehouse_user': 'Retrieves details for a specific Operations Insights Warehouse user.',
    'get_opsi_configuration': 'Retrieves details for an OPSI configuration resource. Requested configuration item fields and custom-status filters are applied only when configuration items are requested.',
    'get_opsi_data_object': 'Retrieves metadata for an OPSI data object. Use query_opsi_data_object_data to execute a query against the data object.',
    'get_work_request': 'Retrieves status and metadata for a specific Operations Insights work request.',
    'list_addm_db_finding_categories': 'Lists ADDM finding categories for database insight analysis. Use this operation to discover category filter values for ADDM finding queries.',
    'list_addm_db_findings_time_series': 'Lists ADDM finding time series data for specified databases and a time period.',
    'list_addm_db_parameter_categories': 'Lists ADDM database parameter categories for specified databases. Use this operation to discover category filters for parameter history analysis.',
    'list_addm_db_recommendation_categories': 'Lists ADDM recommendation categories for specified databases. Use this operation to discover category filters for recommendation analysis.',
    'list_addm_db_recommendations_time_series': 'Lists ADDM recommendation time series data for specified databases and a time period.',
    'list_addm_dbs': 'Lists database information available for ADDM analysis.',
    'list_awr_database_snapshots': 'Lists AWR snapshots for a specified database in an AWR Hub.',
    'list_awr_databases': 'Lists databases and snapshot summary details available in an AWR Hub.',
    'list_awr_hub_objects': 'Lists objects stored for a specified AWR Hub source. Use get_awr_hub_object to retrieve a selected object body.',
    'list_awr_hub_sources': 'Lists source database registrations for AWR Hubs.',
    'list_awr_hubs': 'Lists AWR Hub resources by compartment or identifier. These resources are expected to be in the root compartment.',
    'list_awr_snapshots': 'Lists AWR snapshots for a specified source database in an AWR Hub. The optional time range must not exceed one day; without time bounds, the default range is the last day.',
    'list_chargeback_plan_reports': 'Lists Operations Insights chargeback plan reports for a resource.',
    'list_chargeback_plans': 'Lists Operations Insights chargeback plans.',
    'list_database_configurations': 'Lists database insight configuration records by compartment or database insight id. This returns configuration metadata, not database performance metrics.',
    'list_database_insights': 'Lists database insight resources in a compartment or by exact insight id. Use this operation to discover databases enabled in Operations Insights before calling database metric, forecast, or utilization summary operations.',
    'list_enterprise_manager_bridges': 'Lists Operations Insights Enterprise Manager bridges by compartment or identifier. Recursive compartment search can include bridges in subcompartments.',
    'list_exadata_configurations': 'Lists Exadata insight configuration records by compartment or Exadata insight id. This returns configuration metadata, not Exadata usage metrics.',
    'list_exadata_insights': 'Lists Exadata insight resources in a compartment or by exact insight id. Use this operation to discover Exadata systems enabled in Operations Insights before calling Exadata capacity, usage, forecast, or utilization summary operations.',
    'list_host_configurations': 'Lists host insight configuration records by compartment or host insight id. This returns configuration metadata, not host performance metrics.',
    'list_host_insights': 'Lists host insight resources in a compartment or by exact insight id. Use this operation to discover hosts enabled in Operations Insights before calling host CPU, memory, disk, network, storage, process, or recommendation summary operations.',
    'list_hosted_entities': 'Lists hosted entity details for host insights. Use this operation to identify databases or other entities hosted on a selected host.',
    'list_importable_agent_entities': 'Lists Management Agent entities that are available to create a new host insight. Returned agents are active and are not already associated with an existing host insight.',
    'list_importable_compute_entities': 'Lists compute instances running Oracle Cloud Agent that are available to create a new host insight.',
    'list_importable_enterprise_manager_entities': 'Lists Enterprise Manager entities that can be imported through an Operations Insights Enterprise Manager bridge and have not already been imported.',
    'list_news_reports': 'Lists scheduled Operations Insights news report resources by compartment or identifier before retrieving, updating, or inspecting delivery settings.',
    'list_operations_insights_private_endpoints': 'Lists Operations Insights private endpoints by compartment, VCN, endpoint identifier, RAC usage, or lifecycle state before retrieving or updating a selected endpoint.',
    'list_operations_insights_warehouse_users': 'Lists Operations Insights Warehouse users by compartment or identifier. These resources are expected to be in the root compartment.',
    'list_operations_insights_warehouses': 'Lists Operations Insights Warehouse resources by compartment or identifier. Only one warehouse is expected per tenant, and it is expected in the root compartment.',
    'list_opsi_configurations': 'Lists OPSI configuration resources by display name, lifecycle state, or configuration type before retrieving configuration item details.',
    'list_opsi_data_objects': 'Lists OPSI data objects available to query in a compartment. Use get_opsi_data_object for object metadata and query_opsi_data_object_data to retrieve rows.',
    'list_sql_plans': 'Lists SQL execution plan XML from the SQL Warehouse for a given SQL execution plan. The response is currently limited to a single plan and requires databaseId or database insight id.',
    'list_sql_texts': 'Retrieves full SQL text from the SQL Warehouse for a SQL identifier in a compartment and, when requested, its subcompartments.',
    'list_warehouse_data_objects': 'Lists Warehouse data objects such as views and tables based on query parameters. Use query_warehouse_data_object_data to query rows from a selected object.',
    'list_work_request_errors': 'Lists errors for a specific Operations Insights work request.',
    'list_work_request_logs': 'Lists log entries for a specific Operations Insights work request.',
    'list_work_requests': 'Lists Operations Insights work requests in a compartment or by identifier. Optional resource filters narrow the results to one target or related resource.',
    'query_opsi_data_object_data': 'Queries an OPSI data object and returns result rows. The request must provide either analysisTimeInterval or both timeIntervalStart and timeIntervalEnd.',
    'query_warehouse_data_object_data': 'Queries Warehouse data objects such as views and tables and returns result rows available to the authorized Operations Insights Warehouse user.',
    'summarize_addm_db_findings': 'Summarizes ADDM findings for specified databases over a time period.',
    'summarize_addm_db_parameter_changes': 'Summarizes AWR database parameter change history for one specified parameter. Use summarize_addm_db_parameters to identify parameters that changed during a period.',
    'summarize_addm_db_parameters': 'Summarizes database parameter history for specified databases, including whether parameter values changed during the requested time period. This does not return individual change records.',
    'summarize_addm_db_recommendations': 'Summarizes ADDM recommendations for specified databases over a time period.',
    'summarize_addm_db_schema_objects': 'Summarizes ADDM schema object details for specified databases and object identifiers.',
    'summarize_addm_db_sql_statements': 'Summarizes ADDM SQL statement details for specified databases and SQL identifiers.',
    'summarize_awr_database_cpu_usages': 'Summarizes AWR CPU resource limits and CPU usage metrics for a specified AWR database. Metric granularity depends on the requested time range.',
    'summarize_awr_database_metrics': 'Summarizes AWR metric samples for a specified database, grouped by time for each requested metric.',
    'summarize_awr_database_parameter_changes': 'Summarizes detailed AWR change history for one database parameter, including previous value, current value, and snapshot or time range.',
    'summarize_awr_database_parameters': 'Summarizes database parameter history for a specified AWR database, including whether each parameter changed, differs from the default, or was modified at the system level. Use summarize_awr_database_parameter_changes for detailed history of one parameter.',
    'summarize_awr_database_snapshot_ranges': 'Summarizes continuous AWR snapshot ranges for a specified AWR Hub.',
    'summarize_awr_database_sysstats': 'Summarizes AWR SYSSTAT sample data for a specified database, grouped by time for each statistic.',
    'summarize_awr_database_top_wait_events': 'Summarizes top AWR wait events for a specified database.',
    'summarize_awr_database_wait_event_buckets': 'Summarizes AWR wait event data into frequency buckets for a specified database.',
    'summarize_awr_database_wait_events': 'Summarizes AWR wait event sample data for a specified database, grouped by time for each event.',
    'summarize_awr_sources_summaries': 'Summarizes AWR source database information for AWR Hubs.',
    'summarize_configuration_items': 'Summarizes applicable OPSI configuration items for a configuration type and compartment. Optional field filters determine which configuration item fields are returned.',
    'summarize_database_insight_resource_capacity_trend': 'Summarizes database insight resource capacity time series, including capacity and base capacity, for the requested period. This operation supports up to two years and is not paginated.',
    'summarize_database_insight_resource_forecast_trend': 'Summarizes historical usage and forecast trends for database CPU or storage resources. Use this operation for projected capacity questions rather than current utilization only.',
    'summarize_database_insight_resource_statistics': 'Summarizes per-database resource statistics such as usage, capacity, utilization percentage, base capacity, and auto-scaling state.',
    'summarize_database_insight_resource_usage': 'Summarizes aggregate database resource usage, capacity, and usage change over a requested time period. Use resource_usage_trend for time-series points.',
    'summarize_database_insight_resource_usage_trend': 'Summarizes database resource usage and capacity as time-series data for a requested period. This operation supports up to two years and is not paginated.',
    'summarize_database_insight_resource_utilization_insight': 'Summarizes current and projected database resource utilization insights, including high and low utilization classifications.',
    'summarize_database_insight_tablespace_usage_trend': 'Summarizes database tablespace usage and capacity as time-series data, broken down by tablespace name. The request must identify the database by databaseId or database insight id.',
    'summarize_exadata_insight_resource_capacity_trend': 'Summarizes Exadata resource capacity time-series data for databases, hosts, storage servers, or disk groups in a selected Exadata system.',
    'summarize_exadata_insight_resource_capacity_trend_aggregated': 'Summarizes aggregated Exadata resource capacity time-series data for an Exadata system or fleet.',
    'summarize_exadata_insight_resource_forecast_trend': 'Summarizes historical usage and forecast trends for Exadata databases, hosts, storage servers, or disk groups.',
    'summarize_exadata_insight_resource_forecast_trend_aggregated': 'Summarizes aggregated Exadata historical usage and forecast trends across an Exadata system or fleet.',
    'summarize_exadata_insight_resource_statistics': 'Summarizes Exadata resource statistics such as usage, capacity, utilization percentage, and usage change for databases, hosts, storage servers, or disk groups.',
    'summarize_exadata_insight_resource_usage': 'Summarizes Exadata resource usage and usage change over a requested time period for databases, hosts, or storage servers.',
    'summarize_exadata_insight_resource_usage_aggregated': 'Summarizes aggregated Exadata resource usage and usage change over a requested time period.',
    'summarize_exadata_insight_resource_utilization_insight': 'Summarizes current and projected Exadata resource utilization insights for databases, hosts, or storage servers.',
    'summarize_exadata_members': 'Lists software and hardware inventory for an Exadata system, including Exadata members known to Operations Insights.',
    'summarize_host_insight_disk_statistics': 'Summarizes disk usage, size, and unallocated capacity for a host insight over the requested time interval. Use this operation for per-disk storage capacity questions.',
    'summarize_host_insight_host_recommendation': 'Summarizes host recommendations, when available, for a host insight.',
    'summarize_host_insight_io_usage_trend': 'Summarizes host I/O usage as time-series data broken down by I/O interface.',
    'summarize_host_insight_network_usage_trend': 'Summarizes host network usage as time-series data broken down by network interface.',
    'summarize_host_insight_resource_capacity_trend': 'Summarizes host resource capacity time-series data for a requested period. This operation supports up to two years and is not paginated.',
    'summarize_host_insight_resource_forecast_trend': 'Summarizes historical usage and forecast trends for host CPU or memory resources. Use this operation for projected capacity questions rather than current utilization only.',
    'summarize_host_insight_resource_statistics': 'Summarizes per-host resource statistics such as usage, capacity, utilization percentage, usage change, and load.',
    'summarize_host_insight_resource_usage': 'Summarizes aggregate host resource usage, capacity, and usage change over a requested time period. Use resource_usage_trend for time-series points.',
    'summarize_host_insight_resource_usage_trend': 'Summarizes host resource usage and capacity as time-series data for a requested period. This operation supports up to two years and is not paginated.',
    'summarize_host_insight_resource_utilization_insight': 'Summarizes current and projected host resource utilization insights, including high and low utilization classifications.',
    'summarize_host_insight_storage_usage_trend': 'Summarizes host storage usage as time-series data broken down by filesystem.',
    'summarize_host_insight_top_processes_usage': 'Summarizes top process resource usage on a host for a specific timestamp. Processes are sorted by the requested CPU, memory, or virtual memory metric.',
    'summarize_host_insight_top_processes_usage_trend': 'Summarizes top process resource usage on a host as time-series data. Processes are sorted by the requested CPU, memory, or virtual memory metric.',
    'summarize_operations_insights_warehouse_resource_usage': 'Summarizes resources used by an Operations Insights Warehouse. Only one warehouse is expected per tenant, and it is expected in the root compartment.',
    'update_awr_hub': 'Updates mutable configuration for an AWR Hub resource, such as display metadata or hub connection settings.',
    'update_awr_hub_source': 'Updates mutable configuration for an AWR Hub source database registration, such as display metadata or source registration settings.',
    'update_chargeback_plan': 'Updates one or more attributes of a chargeback plan.',
    'update_chargeback_plan_report': 'Updates one or more attributes of a chargeback plan report.',
    'update_database_insight': 'Updates mutable configuration for a database insight, such as display metadata, tags, or source-specific configuration. This operation changes configuration only and does not retrieve performance metrics.',
    'update_enterprise_manager_bridge': 'Updates mutable configuration for an Operations Insights Enterprise Manager bridge, such as display metadata or bridge connection settings.',
    'update_exadata_insight': 'Updates mutable configuration for an Exadata insight, such as display metadata, tags, or source-specific configuration. This operation changes configuration only and does not retrieve Exadata metrics.',
    'update_host_insight': 'Updates mutable configuration for a host insight, such as display metadata, tags, or source-specific configuration. This operation changes configuration only and does not retrieve host performance metrics.',
    'update_news_report': 'Updates mutable configuration for a news report, such as report content selection, locale, schedule, or notification target.',
    'update_operations_insights_private_endpoint': 'Updates one or more attributes of an Operations Insights private endpoint.',
    'update_operations_insights_warehouse': 'Updates mutable configuration for an Operations Insights Warehouse, such as display metadata or warehouse connection settings. Only one warehouse is expected per tenant, and it is expected in the root compartment.',
    'update_operations_insights_warehouse_user': 'Updates mutable configuration for an Operations Insights Warehouse user, such as user metadata or access-related configuration.',
    'update_opsi_configuration': 'Updates an OPSI configuration resource.',
}
